dozi_blog/dozi_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dozi_blog/main/urls.py
from django.urls import path
from . import views


app_name = 'main'


urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('<int:post_id>/comment/', views.post_comment, name='post-comment'),
]

dozi_blog/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import PIL



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

        

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    image = models.ImageField(upload_to='post_image', blank=True, null=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()


    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]


    def __str__(self):
        return self.title

    
    def get_absolute_url(self):
        return reverse('main:post-detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)   # allows for deactivation of inappropriate comments in the admin


    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

dozi_blog/main/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

dozi_blog/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST



# Display all posts
def post_list(request):
    post_list = Post.published.all()
    # Paginate with 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'main/post/list.html', {'posts': posts})





# Display single post
def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)  # List of active comments for this post
    form = CommentForm()  # Form for users to comment
    return render(request, 'main/post/detail.html', {'post': post, 'comments': comments, 'form': form})




# Share post via email
def post_share(request, post_id):
    # Retrieve post by ID
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url} {cd['name']} comments: {cd['comments']}"
            send_mail(subject, message, 'chidozieamefule@googlemail.com', [cd['to']])
            sent = True
    
    else:
        form = EmailPostForm()
    return render(request, 'main/post/share.html', {'form': form, 'post': post, 'sent': sent})



# Adding Comments
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post  # Assign the post to the comment
        comment.save()
    return render(request, 'main/post/comment.html', {'post': post, 'form': form, 'comment': comment})



    

dozi_blog/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    

    <nav class="navbar navbar-expand-lg bg-body-secondary text-center">
        <div class="container-fluid mx-auto">
          <a class="navbar-brand" href="#"><h2>DOZI-BLOG</h2></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Contact</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

dozi_blog/main/templates/main/post/comment.html
{% extends 'main/base.html' %}

{% block title %}Add Comment{% endblock title %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "main/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

dozi_blog/main/templates/main/post/detail.html
{% extends 'main/base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<div class="card-body mt-4 container">
    {% if post.image %}
        <img src="{{ post.image.url }}" class="img-fluid">
    {% else %}
        <div class="card-img-top bg-light text-secondary text-center py-3" style="width:600px; height: 400px;">
            No Image Available
        </div>
    {% endif %}
    
    <h2 class="mt-4 text-center">{{ post.title }}</h2>

    {{ post.body|linebreaks }}
    <p class="date fw-lighter">Published {{ post.publish|date:"j F, Y" }} by {{ post.author }}</p>
    
    <p>
        <a href="{% url 'main:post-share' post.id %}">Share this post</a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment bg-light">
            <p class="info">
                {{ comment.name }} - 
                {{ comment.created|date:"j F, Y" }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>There are no comments.</p>
        {% endfor %}
        {% include "main/post/includes/comment_form.html" %}
    
</div>
{% endblock content %}

dozi_blog/main/templates/main/post/includes/comment_form.html
{%  load crispy_forms_tags %}



<div style="min-height: 100vh;">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card mx-auto">
                <div class="card-body">
                    <h3>Add a new comment</h3>
                    <form action="{% url 'main:post-comment' post.id %}" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <p><input type="submit" value="Add Comment"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

dozi_blog/main/templates/main/post/list.html
{% extends 'main/base.html' %}

{% block title %}Blog{% endblock title %}

{% block content %}
    <div class="d-flex flex-column align-items-center mt-4">
        {% for post in posts %}
            <div class="card border-info mb-3">
                <div class="card-body" style="width: 38rem;">
                    <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                    
                    
                    {% if post.image %}
                        <img src="{{ post.image.url }}" style="width: 150px; height: 100px;">
                    {% else %}
                        <!-- Handle the case when there is no image -->
                        <p>No image available</p>
                    {% endif %}
                    
                    
                    {{ post.body|truncatewords:30|linebreaks }}
                    <p class="date fw-lighter">Published {{ post.publish|date:"j F, Y" }} by {{ post.author }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include "pagination.html" with page=posts %}
{% endblock content %}

dozi_blog/main/templates/main/post/share.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block title %}Share a post{% endblock title %}

{% block content %}

    {% if sent %}
        <h4>Email successfully sent</h4>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
    <div class="d-flex align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="row">
            <div class="col-md-6">
                <div class="card mx-auto" style="width: 40rem;">
                    <div class="card-body">
                        <h3 class="card-title mb-3">Share "{{ post.title }}" by email</h3>
                        <form method="post">
                            {% csrf_token %}

                            {{ form|crispy }}
                            <button class="btn btn-primary" type="submit">Send Email</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endif %}



{% endblock content %}

dozi_blog/main/templates/pagination.html
<div class="pagination d-flex flex-column align-items-center"> 
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>